[_]
schema-version = "0.2" # 必须设置，schema version 0.1不支持配置build env

[[io.buildpacks.build.env]]
    name = "MAVEN_OPTS"
    value = "-Xms128m –Xmx512m"
[[io.buildpacks.build.env]]
    name = "构建环境变量2"
    value = "构建环境变量2的值"
