SecurityGroupPorts:
- 80
RuntimeType: Container
ServicePorts:
- 80
ServiceType: private
ArtifactSourceType: Buildpacks
RepoName: aliyun-computenest/java-springboot-demo
ServiceBuildRegion: ap-southeast-1
RegionId: cn-hangzhou
CustomParameters: []
Owner: wenle
Branch: main
Platform: github
